---
swagger: 2.0
info:
  version: 1.1
  title: product-service
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /products:
    get:
      summary: Returns all products
      parameters: []
      responses:
        "200":
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
  /products/{productId}:
    get:
      summary: Returns product by product id
      parameters:
      - name: productId
        in: path
        required: true
        type: string
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/Product'
        "404":
          description: product was not found
definitions:
  Product:
    properties:
      id:
        type: string
      title:
        type: string
      description:
        type: string
      count:
        type: integer
      price:
        type: number
